name: Go
on: [push]
jobs:

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build and test run
      if: startsWith(matrix.os, 'windows') != true
      env:
       APP: dist/app-$${{ matrix.os }}
      run: |
        go build -v -o dist/$APP .
        ./$APP

    - name: Build and test run (windows)
      if: startsWith(matrix.os, 'windows')
      env:
       APP: dist/app-$${{ matrix.os }}.exe
      run: |
        go build -v -o dist/%APP% .
        .\dist\%APP%

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

